import React, { useState, useEffect } from "react";
import Head from "next/head";
import {
  Button,
  Space,
  Row,
  Col,
  Image,
  Form,
  Radio,
  Statistic,
  InputNumber,
  Tabs,
  Descriptions,
  Comment,
  List,
  Tooltip,
} from "antd";
import { useRouter } from "next/router";
import Header from "@/components/header";
import Footer from "@/components/footer";

import moment from "moment";

import {
  FacebookFilled,
  TwitterOutlined,
  WeiboOutlined,
  CodepenOutlined,
  EyeOutlined,
} from "@ant-design/icons";

import styles from "@/styles/index.module.scss";

export default function Home() {

  const router = useRouter();
  const { id, cate } = router.query;

  const [form] = Form.useForm();
  const { TabPane } = Tabs;

  const [product, setProduct] = useState({
    product_name: '',
    product_img: '',
    price: 0,
    original_price: 0
  })

  useEffect(() => {
    console.log(id);
    if (typeof window !== 'undefined') {
      const data = JSON.parse(window.localStorage.getItem('km-product'))
      setProduct(data)
    }
  }, [id]);

  const onFinish = (values: any) => {
    console.log("Success:", values);
  };
  function callback(key) {
    console.log(key);
  }

  const checkout = () => {
    window.localStorage.setItem("km-cart", JSON.stringify([product]));
  };

  return (
    <div>
      <Head>
        <title>Komi</title>
        <meta name="description" content="Generated by Komi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main className={styles["kz-main"]}>
        <Row gutter={24}>
          <Col span={10}>
            <Image src={product.product_img} preview={false}/>
          </Col>
          <Col span={12} offset={2}>
            <h3>{product.product_name}</h3>
            <Statistic
              value={product.price}
              precision={2}
              valueStyle={{ color: "#3f8600" }}
              prefix="$"
            />
            <Space size={12} className={styles["kz-original-price-container"]}>
              <span className={styles["kz-original-price"]}>${product.original_price}</span>
              <span>30％OFF</span>
            </Space>
            <div>
              <Space>
                <CodepenOutlined />
                <span>27 inventory</span>
              </Space>
            </div>
            <div className={styles["kz-original-price-container"]}>
              <Space>
                <EyeOutlined />
                <span>6 view</span>
              </Space>
            </div>
            <Form form={form} onFinish={onFinish} layout="vertical">
              <Form.Item initialValue="a" name="color" label="color">
                <Radio.Group>
                  <Space size={12}>
                    <Radio.Button value="a">white</Radio.Button>
                    <Radio.Button value="b">black</Radio.Button>
                    <Radio.Button value="c">yellow</Radio.Button>
                  </Space>
                </Radio.Group>
              </Form.Item>
              <Form.Item initialValue="b" name="size" label="size">
                <Radio.Group>
                  <Space size={12}>
                    <Radio.Button value="a">S</Radio.Button>
                    <Radio.Button value="b">M</Radio.Button>
                    <Radio.Button value="c">L</Radio.Button>
                    <Radio.Button value="d">XL</Radio.Button>
                  </Space>
                </Radio.Group>
              </Form.Item>
              <Form.Item>
                <InputNumber size="large" min={1} max={10} defaultValue={1} />
                <Button
                  type="primary"
                  danger
                  block
                  size="large"
                  className={styles["kz-product-btn-buy"]}
                  href="/order/confirm/86697?step=contact_information"
                  htmlType="submit"
                  onClick={checkout}
                >
                  Checkout
                </Button>
              </Form.Item>
            </Form>
            <Space size={18}>
              <span>share</span>
              <FacebookFilled />
              <TwitterOutlined />
              <WeiboOutlined />
            </Space>
            <div>
              <Image width={440} preview={false} src="/pay.png" />
            </div>
          </Col>
        </Row>
        <Tabs defaultActiveKey="1" onChange={callback}>
          <TabPane tab="product description" key="1">
            <Descriptions column={4}>
              <Descriptions.Item label="brand name" span={4}>
                CHAMPION
              </Descriptions.Item>
              <Descriptions.Item label="brand">CHAMPION</Descriptions.Item>
              <Descriptions.Item label="Classification of fabric">knit</Descriptions.Item>
              <Descriptions.Item label="The article number">C3-P302</Descriptions.Item>
              <Descriptions.Item label="Basic style">Youth pop</Descriptions.Item>
              <Descriptions.Item label="Market year and season">
                2020 summer
              </Descriptions.Item>
              <Descriptions.Item label="thickness">conventional</Descriptions.Item>
              <Descriptions.Item label="Material components">cotton 100%</Descriptions.Item>
            </Descriptions>
          </TabPane>
          <TabPane tab="comment" key="2">
          </TabPane>
        </Tabs>
      </main>
      <Footer />
    </div>
  );
}
