import React, { useState, useEffect } from "react";
import Head from "next/head";
// import Image from "next/image";
import { useRouter } from "next/router";
import { Result, Button } from "antd";

export default function Home() {
  const router = useRouter();

  useEffect(() => {}, []);
  return (
    <div>
      <Head>
        <title>Komi</title>
        <meta name="description" content="Generated by Komi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Result
          status="success"
          title="Successfully pay the order"
          subTitle="Order number: 2017182818828182881 Cloud server configuration takes 1-5 minutes, please wait."
          extra={[
            <Button type="primary" key="index" href="/">
              Back home
            </Button>,
            <Button key="orderDetail" href="/order/detail/2017182818828182881">view the order</Button>,
          ]}
        />
      </main>
    </div>
  );
}
