import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Button, Input, Checkbox, Form, message } from "antd";
import { useRouter } from "next/router";
import Header from "@/components/header";
import Footer from "@/components/footer";

import {
  FacebookFilled,
  TwitterOutlined,
  WeiboOutlined,
  CodepenOutlined,
  EyeOutlined,
} from "@ant-design/icons";

import styles from "@/styles/index.module.scss";

export default function Home() {
  const router = useRouter();
  const { id } = router.query;

  const [form] = Form.useForm();

  const [submitLoading, setSubmitLoading] = useState(false);

  useEffect(() => {
    console.log(id);
  }, [id]);

  const layout = {
    labelCol: { span: 8 },
    wrapperCol: { span: 8 },
  };
  const tailLayout = {
    wrapperCol: { offset: 8, span: 16 },
  };

  const onFinish = (values: any) => {
    if (submitLoading) return;
    setSubmitLoading(true);
    setTimeout(() => {
      setSubmitLoading(false);
      message.error('login faild, please try again later')
    }, 1000)
    console.log("Success:", values);
  };

  return (
    <div>
      <Head>
        <title>Komi</title>
        <meta name="description" content="Generated by Komi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles["kz-main"]}>
        <h1 style={{ textAlign: "center", marginBottom: 48 }}>Login</h1>
        <Form
          {...layout}
          name="basic"
          initialValues={{ remember: true }}
          onFinish={onFinish}
        >
          <Form.Item
            label="Email"
            name="email"
            rules={[{ required: true, message: "Please input your Email!" }]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="Password"
            name="password"
            rules={[{ required: true, message: "Please input your password!" }]}
          >
            <Input.Password />
          </Form.Item>

          <Form.Item {...tailLayout} name="remember" valuePropName="checked">
            <Checkbox>Remember me</Checkbox>
          </Form.Item>

          <Form.Item {...tailLayout}>
            <Button type="primary" htmlType="submit" loading={submitLoading}>
              Submit
            </Button>
          </Form.Item>
        </Form>
      </main>
      <Footer />
    </div>
  );
}
