import React, { useState, useEffect } from 'react'
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

export default function Home() {
  
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    console.log(id);
  }, [id])
  return (
    <div>
      <Head>
        <title>Komi</title>
        <meta name="description" content="Generated by Komi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>您的订单号为：{id}</h1>
      </main>
    </div>
  );
}
